config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  resources :kittens

  root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

    def index
        @kittens = Kitten.all
    end

    def show
        @kitten = Kitten.find(params[:id])
    end

    def new
        @kitten = Kitten.new
    end

    def create
        @kitten = Kitten.new(kitten_params)

        if @kitten.save
            flash[:success] = "Kitten was created successfully, meow!"
            redirect_to @kitten
        else
            flash.now[:error] = "Error creating kitten!"
            render :new
        end
    end

    def edit
        @kitten = Kitten.find(params[:id])
    end

    def update
        @kitten = Kitten.find(params[:id])

        if @kitten.update(kitten_params)
            redirect_to @kitten, flash[:success] = "Kitten was updated successfully, they do have nine lives!"
        else
            render :edit, flash.now[:error] = "Try again! And slower this time", status: :unprocessable_entity
        end
    end

    def destroy
        @kitten = Kitten.find(params[:id])

        @kitten.destroy!
        flash[:success] = "Kitten was deleted successfully, I think it's ran away!"
        redirect_to root_path
    end


    private


    def kitten_params
        params.require(:kitten).permit(:name, :age, :cuteness, :softness)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: @kitten do |form| %>
    <%= form.label :name, "Enter name" %>
    <%= form.text_field :name %><br>

    <%= form.label :age, "Age" %>
    <%= form.number_field :age %><br>

    <%= form.label :cuteness, "Cuteness" %>
    <%= form.number_field :cuteness, min: 1, max: 10 %><br>

    <%= form.label :softness, "Softness" %>
    <%= form.number_field :softness, min: 1, max: 10 %><br>

    <%= form.submit "Save Kitten" %>

    
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render 'form' %>
<%= link_to "Delete Kitten", kitten_path(@kitten), method: :delete, data: { confirm: "Are you sure you want to delete this kitten?" } %>

app/views/kittens/index.html.erb
<h1>Welcome to Index</h1>

    <%= link_to "Create New Kitten", new_kitten_path %>


    <% @kittens.each_with_index do |kitten, index| %>
        <h4>Kitten #<%= index + 1 %></h4>
        <ul>
            <li>
                <h4>Name:  <%= kitten.name %> </h4>
            </li>
            <li>
                <h4>Age: <%= kitten.age %> </h4>
            </li>
            <li>
                <h4>Cuteness: <%= kitten.cuteness %> </h4>
            </li>
            <li>
                <h4>Softness: <%= kitten.softness %> </h4>
            </li>
            <li>
                <%= link_to "View Kitten", kitten_path(kitten) %>
                <%= link_to "Delete Kitten", kitten_path(kitten), method: :delete, data: { confirm: "Are you sure you want to delete this kitten?" } %>
            </li>
        </ul>
    <% end %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render 'form' %>

app/views/kittens/show.html.erb
<h1>Here's your kitten's info</h1>

<h4>Name: </h4>
<p><%= @kitten.name %></p>

<h4>Age: </h4>
<p><%= @kitten.age %></p>

<h4>Cuteness: </h4>
<p><%= @kitten.cuteness %></p>

<h4>Softness: </h4>
<p><%= @kitten.softness %></p>



<%= button_to "Delete Kitten", kitten_path(@kitten), method: :delete, data: { confirm: "Are you sure?" } %><br>
<%= link_to "All Kittens", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Odin Kittens" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>